language: python
services:
  - docker
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install pytest coverage codecov flake8
script:
- flake8
- coverage run -m pytest -s
- codecov
- docker build -t sslhep/servicex_code_gen_funcadl_xaod:${TRAVIS_BRANCH} .

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
deploy:
  provider: script
  script: docker push sslhep/servicex_code_gen_funcadl_xaod:${TRAVIS_BRANCH}
  on:
      all_branches: true
